services:
  dev:
    build:
      context: .
      dockerfile: dockerfiles/train.dockerfile
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./configs:/app/configs
      - ./src:/app/src
    command: ["sh", "-lc", "sleep infinity"]
    tty: true
  train:
    build:
      context: .
      dockerfile: dockerfiles/train.dockerfile
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./configs:/app/configs

  api:
      build:
        context: .
        dockerfile: dockerfiles/api.dockerfile
      volumes:
        - ./src:/app/src        # Dette gjør at koden din oppdateres live
        - ./models:/app/models  # Dette gjør at den finner de tidsstemplede mappene
      ports:
        - "8000:8000"
